/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DummySecond } from "./DummySecond";

export class DummySecondFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DummySecond> {
    return super.deploy(overrides || {}) as Promise<DummySecond>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DummySecond {
    return super.attach(address) as DummySecond;
  }
  connect(signer: Signer): DummySecondFactory {
    return super.connect(signer) as DummySecondFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DummySecond {
    return new Contract(address, _abi, signerOrProvider) as DummySecond;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getDummyIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getNoticePeriod",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "isReadyForUpgrade",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "upgradeParameters",
        type: "bytes",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradeCanceled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradeFinishes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradeNoticePeriodStarted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgradePreparationStarted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "verifyPriorityOperation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102f2806100206000396000f3fe608060405234801561001057600080fd5b506004361061009e5760003560e01c806378b91e701161006657806378b91e7014610137578063871b8ff1146101375780638773334c146101af578063b269b9ae14610137578063ecbc2c3c146101cb5761009e565b80630f8d1dbe146100a357806325394645146100ad5780632a3174f41461011d5780633b154b7314610137578063439fab911461013f575b600080fd5b6100ab6101d3565b005b6100ab600480360360208110156100c357600080fd5b8101906020810181356401000000008111156100de57600080fd5b8201836020820111156100f057600080fd5b8035906020019184600183028401116401000000008311171561011257600080fd5b5090925090506101f9565b610125610239565b60408051918252519081900360200190f35b6100ab61023e565b6100ab6004803603602081101561015557600080fd5b81019060208101813564010000000081111561017057600080fd5b82018360208201111561018257600080fd5b803590602001918460018302840111640100000000831117156101a457600080fd5b509092509050610240565b6101b7610275565b604080519115158252519081900360200190f35b6101256102a2565b6000805467ffffffffffffffff8082166001011667ffffffffffffffff19909116179055565b60008282600081811061020857fe5b919091013560f81c9150600090508383600181811061022357fe5b600294909455509091013560f81c600355505050565b600490565b565b6040805162461bcd60e51b81526020600482015260056024820152646473696e6960d81b604482015290519081900360640190fd5b600061027f6102a7565b67ffffffffffffffff166102916102ac565b67ffffffffffffffff161015905090565b600290565b600090565b60005467ffffffffffffffff169056fea2646970667358221220be9f9234e08e9a011c04a335263c5967b45d785efd710f9ddc40545d62b4092c64736f6c63430007060033";
