/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Operations } from "./Operations";

export class OperationsFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Operations> {
    return super.deploy(overrides || {}) as Promise<Operations>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Operations {
    return super.attach(address) as Operations;
  }
  connect(signer: Signer): OperationsFactory {
    return super.connect(signer) as OperationsFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Operations {
    return new Contract(address, _abi, signerOrProvider) as Operations;
  }
}

const _abi = [
  {
    inputs: [],
    name: "PACKED_FULL_EXIT_PUBDATA_BYTES",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6096610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80635ebcfa95146038575b600080fd5b603e6052565b604051604991906057565b60405180910390f35b606981565b9081526020019056fea264697066735822122095ab8a99b33cebc89c67439ffc1066252db41ec66faf9ed4e1d3097c6d6267be64736f6c63430007060033";
